spring:
  application:
    name: payment-flow
  datasource:
    url: jdbc:postgresql://localhost:5432/flowdb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  servlet:
    context-path: /v1





